name: Android Build OS
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Dogrudan Indirme ve Kurulum
        run: |
          echo "Kuruluma basliyoruz..."
          mkdir -p ~/bin
          curl https://storage.googleapis.com/git-repo-downloads/repo > ~/bin/repo
          chmod a+x ~/bin/repo
          export PATH=~/bin:$PATH
          mkdir -p android-lab
          cd android-lab
          git config --global user.email "mimar@aros.com"
          git config --global user.name "Mimar"
          ~/bin/repo init -u https://android.googlesource.com/platform/manifest -b android-14.0.0_r20
          ~/bin/repo sync -c -j$(nproc) --depth=1
          echo "Sistem hazir!"
