name: Android Build OS
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04
    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Depo ve Hazirlik
        run: |
          mkdir -p ~/bin
          curl https://storage.googleapis.com/git-repo-downloads/repo > ~/bin/repo
          chmod a+x ~/bin/repo
          export PATH=~/bin:$PATH
          mkdir android-lab && cd android-lab
          repo init --partial-clone --no-use-superproject -b android-latest-release -u https://android.googlesource.com/platform/manifest
          repo sync -c -j$(nproc) --depth=1
          echo "Kodlar indi, Mimar'ın mutfağı hazır!"
